"""added deleted_at column in conversation table

Revision ID: 6bf9b0991511
Revises: 57f0b5db6e57
Create Date: 2026-06-14 06:01:00.052046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf9b0991511'
down_revision: Union[str, Sequence[str], None] = '57f0b5db6e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'deleted_at')
    # ### end Alembic commands ###
