"""added active flag to documents

Revision ID: b553cad51b0f
Revises: 91a91d566b14
Create Date: 2026-05-09 14:34:32.458513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b553cad51b0f'
down_revision: Union[str, Sequence[str], None] = '91a91d566b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'documents',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            server_default='true'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_active')
    # ### end Alembic commands ###
